version: "3.3"
 
services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=zeus
      - DB_USER=zeus
      - DB_PASSWORD=zeus2021
      - PORT=3000
    links:
      - db
  db:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=zeus
      - MYSQL_DATABASE=zeus
      - MYSQL_USER=zeus
      - MYSQL_PASSWORD=zeus2021
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8888:80
volumes:
  dbdata: